# Knapsack Problem - Dynamic Programming

## Problem Definition

Maximize the value of items packed into the knapsack without exceeding its total capacity.

Given $n$ items to choose from, each item $i \in 0...n-1$ has a value $v_{i}$ and a
weight $w_{i}$. The knapsack has a limited capacity $K$. Let $x_{i}$ be a variable that is $1$ if you choose to take item $i$ and $0$ if you leave item $i$ behind.

$$\begin{array}{l l} 
\text{maximise:} \quad 
                    & \sum_{i \in 0...n-1} v_{i}x_{i} \\
\text{subject to:} \quad 
                    & \sum_{i \in 0...n-1} w_{i}x_{i} \leq K \\
                    & x_{i} \in \{0,1\} \quad (i \in 0...n-1)
\end{array}
$$

## Data Format Specification

A knapsack input contains $n + 1$ lines. The first line contains two integers, the first is the number of items in the problem, $n$. The second number is the capacity of the knapsack, $K$. The remaining lines present the data for each of the items. Each line, $i \in 0...n-1$ contains two integers, the item's value $v_i$ followed by its weight $w_i$.

Input Format
<div style="border: 1px solid black">
<samp>n K
v_0 w_0
v_1 w_1
...
v_n-1 w_n-1
</samp>
</div>

The output contains a knapsack solution and is made of two lines. 

The first line contains two values $obj$ and $opt$.

$obj$ is the total value of the items selected to go into the knapsack (i.e. the objective value). $opt$ should be $1$ if your algorithm proved optimality and $0$ otherwise. 

The second line is a list of $n$ $0/1$-values, one for each of the $x_i$ variables. This line encodes the solution.

Output Format
<div style="border: 1px solid black">
<samp>obj opt
x_0 x_1 x_2 ... x_n-1
</samp>
</div>

## Dynamic Programming Solution

$$
\begin{array}{l l}
\text{if } w_j \leq k \text{ : } \quad
&O(k,j) = \max ( O(k, j-1), v_j + O(k - w_j, j-1) ) \\
\text{else : } \quad
&O(k,j) = O(k,j-1) \\
\\
\text{note: }
& O(k,0) = 0 \text{ for all k} \\
& k \in 0...K \\
& j \in i \in 0...n-1
\end{array}
$$

In [1]:
import numpy as np

from collections import namedtuple
Item = namedtuple("Item", ['index', 'value', 'weight'])

In [2]:
#Data Preparation
file_location = '.\data\ks_30_0'

In [3]:
items = []

with open(file_location, 'r') as input_data_file:
    iter_input_data_file = iter(input_data_file.readline, '')
    for line_idx, line in enumerate(iter_input_data_file):
        parts = line.split()
        if line_idx == 0:
            item_count = int(parts[0])
            capacity = int(parts[1])
            dp_table = np.zeros((capacity+1, item_count+1), dtype=np.uint64, order='F')
        else:
            items.append(Item(line_idx-1, int(parts[0]), int(parts[1])))
            value = np.uint64(parts[0])
            weight = np.uint64(parts[1])
            for k in range(0, capacity+1):
                if k >= weight:
                    dp_table[k,line_idx] = max(dp_table[k, line_idx - 1] , value + dp_table[k - weight, line_idx - 1])
                else:
                    dp_table[k,line_idx] = dp_table[k, line_idx - 1]

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:17: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [4]:
print(dp_table[-10:-1,-10:-1])

[[99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]
 [99798 99798 99798 99798 99798 99798 99798 99798 99798]]


In [5]:
output_data = str(dp_table[capacity][item_count]) + ' ' + str(0) + '\n'
taken = [0] * item_count

k = capacity

for i in range(item_count,0,-1):
    if dp_table[k, i] != dp_table[k, i-1]:
        taken[i-1] = 1
        k -= items[i-1].weight
        continue
    else:
        continue
        
output_data += ' '.join(map(str, taken))

In [6]:
print(output_data)

99798 0
0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0


In [7]:
print('Sum Value= ' + str(sum(a.value for (a,b) in zip(items,taken) if b == 1)))

print('Sum Weight= ' + str(sum(a.weight for (a,b) in zip(items,taken) if b == 1)))

print('Capacity= ' + str(capacity))

print('Count Items taken= ' + str(sum(taken)))

Sum Value= 99798
Sum Weight= 99846
Capacity= 100000
Count Items taken= 9
